=== Organization-Work/HPE/HCAS/hca_config/hca_docview.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
  xmlns:hcaview="http://www.autonomy.com/find/docview"
  targetNamespace="http://www.autonomy.com/find/docview"
  elementFormDefault="qualified">
  
  	<annotation>
  		<appinfo>HPE Healthcare Analytics</appinfo>
  		<documentation>
  			This schema defines the supported data view of a document to be transformed by admissions.xsl.
  		</documentation>
  	</annotation>
	
	<attributeGroup name="linkedContentAttrs">
		<attribute name="contentDb" type="string"/>
		<attribute name="contentView" type="string"/>
		<attribute name="contentQParams" type="string"/>
		<attribute name="contentTemplate" type="string"/>		
	</attributeGroup>

	<attributeGroup name="fieldBaseAttributes">
		<attribute name="label" type="string" use="required"/>
		<attribute name="queryField" type="string"/>
		<attribute name="outputEscape" type="boolean" default="true"/>	
		<attribute name="styleClass" type="string"/>	
		<attribute name="hlEmbeddedText" type="boolean" default="false"/>	
		<attributeGroup ref="hcaview:linkedContentAttrs"/>
	</attributeGroup>		
	
	
	<complexType name="fieldItem">
		<annotation>
			<documentation>
				Specify fields to be listed in the output as simple name: value pair
			</documentation>
		</annotation>
		<attribute name="name" type="string" use="required"/>
		<attributeGroup ref="hcaview:fieldBaseAttributes"/>
	</complexType>

	<complexType name="sectionItem">
		<attribute name="childName" type="string" use="required"/>
		<attributeGroup ref="hcaview:fieldBaseAttributes"/>
	</complexType>
	
	<complexType name="headerItem">
		<simpleContent>
			<extension base="string">
				<attribute name="styleClass" type="string"/>
			</extension>
		</simpleContent>
	</complexType>
	
	<complexType name="fieldSection">
		<annotation>
			<documentation>
				Specify fields that have multiple instances in the document.
			</documentation>
		</annotation>
		<sequence>
			<element name="header" type="hcaview:headerItem" minOccurs="0"/>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element name="sfield" type="hcaview:sectionItem" minOccurs="0" maxOccurs="unbounded"/>
				<element name="sectionheader" type="hcaview:headerItem" minOccurs="0" maxOccurs="unbounded"/>
				<element name="section" type="hcaview:fieldSection" minOccurs="0" maxOccurs="unbounded"/>				
				<element name="list" type="hcaview:fieldList" minOccurs="0" maxOccurs="unbounded"/>
			</choice>
		</sequence>
		<attribute name="name" type="string" use="required"/>
		<attribute name="styleClass" type="string"/>
		<attribute name="hlEmbeddedText" type="boolean" default="false"/>
		<attribute name="queryField" type="string"/>
	</complexType>
	
	<complexType name="fieldList">
		<annotation>
			<documentation>
				Specify fields to be rendered as a list.
			</documentation>
		</annotation>
		<sequence>
			<element name="sfield" type="hcaview:sectionItem" maxOccurs="unbounded"/>		
		</sequence>
		<attribute name="styleClass" type="string"/>
	</complexType>
		
	<element name="docview">
		<complexType>
			<sequence>
				<element name="viewtab" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="header" type="string" minOccurs="0"/>
							<choice minOccurs="0" maxOccurs="unbounded">
								<element name="field" type="hcaview:fieldItem" minOccurs="0" maxOccurs="unbounded"/>
								<element name="section" type="hcaview:fieldSection" minOccurs="0" maxOccurs="unbounded"/>								
							</choice>
						</sequence>
						<attribute name="name" type="string" use="required"/>
						<attribute name="defaultActive" type="boolean" default="false"/>
						<attribute name="header" type="string"/>
						<attribute name="styleClass" type="string"/>
					</complexType>
				</element>				
			</sequence>
			<attribute name="baseFieldXml" type="string"/>
			<attribute name="docRoot" type="string" use="required"/>
		</complexType>
	</element>
		
	

</schema>

=== Organization-Work/HPE/HCAS/hca_config/docview_admissions.xml
<?xml version="1.0" encoding="UTF-8"?>
<docview xmlns="http://www.autonomy.com/find/docview"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.autonomy.com/find/docview hca_docview.xsd"
    docRoot="DOCUMENT">
    <viewtab name="Encounter Info">
        <field name="INPATIENT/hadm_id" label="Encounter ID"></field>
		<field name="INPATIENT/subject_id" label="Patient ID"></field> 
        <field name="INPATIENT/admit_dt" label="Admission Date"></field>
        <field name="INPATIENT/disch_dt" label="Discharge Date"></field>
        <field name="INPATIENT/admit_mnth" label="Admission Month"></field>
        <field name="INPATIENT/admit_week" label="Admission Week"></field>
    </viewtab>
    <viewtab name="Patient Info">
        <field name="INPATIENT/subject_id" label="Patient ID"></field>        
        <!--field name="INPATIENT/GENDER/VALUE/sex" label="Gender"></field-->
		<field name="INPATIENT/AGE/VALUE/age_at_admission" label="Age At Admission"></field>
        <!--field name="INPATIENT/DEMOGRAPHICS/DEMO/dob" label="Date of Birth"></field>
        <field name="INPATIENT/DEMOGRAPHICS/DEMO/dod" label="Date of Death"></field>
        <field name="INPATIENT/DEMOGRAPHICS/DEMO/AGE_AT_ADMISSION_GRP" label="Admission Age Group"></field>
        <field name="INPATIENT/DEMOGRAPHICS/DEMO/AGE_AT_DEATH" label="Death Age Group"></field-->
        <field name="INPATIENT/EXPIRE/VALUE/hospital_expire" label="Expired in Hospital"></field>
        <field name="INPATIENT/DEMO/religion_descr" label="Religion"></field>
        <field name="INPATIENT/DEMO/admission_source_descr" label="Admission Source"></field>
        <field name="INPATIENT/DEMO/admission_type_descr" label="Admission Type"></field>
        <field name="INPATIENT/DEMO/marital_status_descr" label="Marital Status"></field>
        <field name="INPATIENT/DEMO/overall_payor_group_descr" label="Payer Group"></field>
        <field name="INPATIENT/DEMO/ethnicity_descr" label="Ethnicity"></field>
    </viewtab>
    <viewtab name="Diagnosis Codes">
       	<section name="INPATIENT/CODES/CODE" styleClass="data-section">
			<sfield childName="codedesc" label="Clinical Code Description"></sfield>
			<!--sfield childName="description" label="Description"></sfield-->			
		</section>
    </viewtab>
    <viewtab name="Procedures Codes">
        <section name="INPATIENT/DRGEVENTS/DRG" styleClass="list-section horizontal-list">
            <sfield childName="itemid" label="ID"></sfield>        
            <sfield childName="cost_weight" label="Cost Weight"></sfield>                    
        </section>
    </viewtab>
    <viewtab name="ICU Visits">
        <section name="INPATIENT/ICUVISITS/ICUSTAY" styleClass="data-section">
            <header styleClass="section-header">ICU Visit:</header>
            <sfield childName="icustay_first_careunit" label="First Care Unit"></sfield>
            <sfield childName="icustay_last_careunit" label="Last Care Unit"></sfield>
            <sfield childName="icustay_los" label="Length of Stay"></sfield>
            <sfield childName="icustay_intime" label="In Time"></sfield>
            <sfield childName="icustay_outtime" label="Out Time"></sfield>             
            <sectionheader styleClass="section-header">Medications:</sectionheader>
            <section name="MEDEVENTS/EVENT" styleClass="data-section">
					<sfield childName="charttime" label="Chart time"></sfield>
					<sfield childName="medication" label="Medication"></sfield>
					<sfield childName="realtime" label="Real time"></sfield>
					<sfield childName="caregiver" label="Care Giver"></sfield>
					<sfield childName="careunit" label="Care Unit"></sfield>
					<sfield childName="volume" label="Volume"></sfield>
					<sfield childName="dose" label="Dose"></sfield>
					<sfield childName="doseuom" label="Dose UOM"></sfield>                  
              
            </section>            
        </section>
    </viewtab>
    <viewtab name="POE Events">
        <section name="INPATIENT/POEEVENTS/EVENT" styleClass="data-section">
			<header styleClass="section-header">POE Order:</header>
			<sfield childName="start_dt" label="Start Date"></sfield>
			<sfield childName="stop_dt" label="Stop Date"></sfield>
			<sfield childName="enter_dt" label="Enter Date"></sfield>
			<sfield childName="medication" label="Med"></sfield>            
			<sfield childName="procedure_type" label="Procedure Type"></sfield>
			<sfield childName="status" label="Status"></sfield>
			<sfield childName="route" label="Route"></sfield>
			<sfield childName="frequency" label="Frequency"></sfield>
			<sfield childName="dispense_sched" label="Dispense Sched"></sfield>        
			<sfield childName="iv_fluid" label="IV fluid"></sfield>
			<sfield childName="iv_rate" label="IV rate"></sfield>
			<sfield childName="infusion_type" label="Infusion Type"></sfield>
			<sfield childName="sliding_scale" label="Sliding Scale"></sfield>
			<sfield childName="doses_per_24hrs" label="Doses/24Hrs"></sfield>
			<sfield childName="duration" label="Duration"></sfield>
			<sfield childName="duration_intvl" label="Duration Interval"></sfield>
			<sfield childName="expiration_val" label="Expiration Value"></sfield>
			<sfield childName="expiration_unit" label="Expiration Unit"></sfield>
			<sfield childName="expiration_dt" label="Expiration Date"></sfield>
			<sfield childName="label_instr" label="Label Instruction"></sfield>
			<sfield childName="additional_instr" label="Additional Instruction"></sfield>
			<sfield childName="md_add_instr" label="MD Additional Instruction"></sfield>
			<sfield childName="rnurse_add_instr" label="Nurse Additional Instruction"></sfield>
        </section>
    </viewtab>
    <!--viewtab name="Lab Events">
        <section name="INPATIENT/LABEVENTS/EVENT" styleClass="list-section horizontal-list">
            <list>
                <sfield childName="itemid" label="Lab Item ID"></sfield>
				<sfield childName="charttime" label="Charttime"></sfield>
				<sfield childName="valuenum" label="Value"></sfield>
				<sfield childName="valueuom" label="Value UOM"></sfield>
				<sfield childName="flag" label="Flag"></sfield>
            </list>
        </section>
    </viewtab-->
    <viewtab name="Notes" defaultActive="true">
        <section name="INPATIENT/NOTES/NOTE" styleClass="data-section">
            <sfield childName="title" label="Title"></sfield>
            <sfield childName="category" label="Type"></sfield>
            <sfield childName="charttime" label="Chart Time"></sfield>
            <sfield childName="cuid_label" label="Care Unit"></sfield>
            <sfield childName="cgid_label" label="Care Giver"></sfield>
            <sfield childName="text" label="Note"></sfield>
        </section>
    </viewtab>    
</docview>

=== Organization-Work/HPE/HCAS/hca_config/docview_patients.xml
<?xml version="1.0" encoding="UTF-8"?>
<docview xmlns="http://www.autonomy.com/find/docview"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.autonomy.com/find/docview hca_docview.xsd"
    docRoot="DOCUMENT">
	<viewtab name="Patient Info" defaultActive="true">
        <field name="PATIENT/subject_id" label="Patient ID"></field>        
        <field name="PATIENT/DEMOGRAPHICS/DEMO/religion_descr" label="Religion"></field>
        <field name="PATIENT/DEMOGRAPHICS/DEMO/marital_status_descr" label="Marital Status"></field>
        <field name="PATIENT/DEMOGRAPHICS/DEMO/overall_payor_group_descr" label="Payer Group"></field>
        <field name="PATIENT/DEMOGRAPHICS/DEMO/ethnicity_descr" label="Ethnicity"></field>
    </viewtab>
    <viewtab name="Admissions" defaultActive="false">
		<header styleClass="section-header">Admissions:</header>
		<section name="PATIENT/ADMISSIONS/INPATIENT" styleClass="data-section">			
			<sfield childName="hadm_id" label="Encounter ID"></sfield>
			<sfield childName="subject_id" label="Patient ID"></sfield> 
			<sfield childName="admit_dt" label="Admission Date"></sfield>
			<sfield childName="disch_dt" label="Discharge Date"></sfield>	
			<header styleClass="section-header">Diagnosis codes:</header>
			<section name="CODES/CODE" styleClass="data-section">
				<sectionheader styleClass="sub-section-header">Code:</sectionheader>
				<sfield childName="code" label="Clinical Code"></sfield>
				<sfield childName="description" label="Description"></sfield>			
			</section>
			<header styleClass="section-header">DRGs:</header>			
			<section name="DRGEVENTS/DRG" styleClass="data-section">
			    <sectionheader styleClass="sub-section-header">Code:</sectionheader>
				<sfield childName="itemid" label="ID"></sfield>        
				<sfield childName="cost_weight" label="Cost Weight"></sfield>                    
			</section>
			<header styleClass="section-header">ICU Visits:</header>	
			<section name="ICUVISITS/ICUSTAY" styleClass="data-section">
				<sectionheader styleClass="sub-section-header">Visit:</sectionheader>
				<sfield childName="icustay_first_careunit" label="First Care Unit"></sfield>
				<sfield childName="icustay_last_careunit" label="Last Care Unit"></sfield>
				<sfield childName="icustay_los" label="Length of Stay"></sfield>
				<sfield childName="icustay_intime" label="In Time"></sfield>
				<sfield childName="icustay_outtime" label="Out Time"></sfield>			          
			</section>
			<header styleClass="section-header">POE(s):</header>
			<section name="POEEVENTS/EVENT" styleClass="list-section horizontal-list">
				<sectionheader styleClass="sub-section-header">POE:</sectionheader>
				<list>
					<sfield childName="medication" label="Med"></sfield>            
					<sfield childName="procedure_type" label="Procedure Type"></sfield>
					<sfield childName="status" label="Status"></sfield>
					<sfield childName="route" label="Route"></sfield>
					<sfield childName="frequency" label="Frequency"></sfield>
					<sfield childName="dispense_sched" label="Dispense Sched"></sfield>
				</list>
			</section>
			<header styleClass="section-header">NOTES:</header>
			<section name="NOTES/NOTE" styleClass="data-section">
				<sectionheader styleClass="sub-section-header">NOTE:</sectionheader>
				<sfield childName="title" label="Title"></sfield>
				<sfield childName="category" label="Type"></sfield>
				<sfield childName="charttime" label="Chart Time"></sfield>
				<sfield childName="cuid" label="Care Unit ID"></sfield>
				<sfield childName="cgid" label="Care Giver ID"></sfield>
				<sfield childName="text" label="Note"></sfield>
			</section>
		</section>	
    </viewtab>	    
</docview>

=== Organization-Work/HPE/HCAS/hcas_java/find-dev/src/main/resources/hca_config/docview_patients_linkContent_Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<docview xmlns="http://www.autonomy.com/find/docview"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.autonomy.com/find/docview hca_docview.xsd"
    docRoot="DOCUMENT">
    <viewtab name="Encounter Info">
        <section name="PATIENT/ADMISSION" styleClass="data-section items-list" >
            <sfield childName="HADM_ID" label="Encounter ID" contentView="admissions" contentQParams="print=fields&amp;printfields=ADMISSION/NOTEEVENT/TEXT"></sfield> 
        </section>
    </viewtab>
    <viewtab name="Patient Info">
        <field name="PATIENT/SUBJECT_ID" label="Patient ID"></field>        
        <field name="PATIENT/SEX" label="Gender"></field>
        <field name="PATIENT/DOB" label="Date of Birth"></field>
        <field name="PATIENT/DOD" label="Date of Death"></field>
        <field name="PATIENT/AGE_AT_ADMISSION" label="Age At Admission"></field>
        <field name="PATIENT/AGE_AT_ADMISSION_GRP" label="Admission Age Group"></field>
        <field name="PATIENT/AGE_AT_DEATH_GRP" label="Death Age Group"></field>
        <field name="PATIENT/HOSPITAL_EXPIRE" label="Expired in Hospital"></field>
        <field name="PATIENT/RELIGION" label="Religion"></field>
        <field name="PATIENT/ADMISSION_SOURCE" label="Admission Source"></field>
        <field name="PATIENT/ADMISSION_TYPE" label="Admission Type"></field>
        <field name="PATIENT/MARITAL_STATUS" label="Marital Status"></field>
        <field name="PATIENT/OVERALL_PAYOR_GROUP" label="Payer Group"></field>
        <field name="PATIENT/ETHNICITY" label="Ethnicity"></field>
    </viewtab>
    
</docview>

=== Organization-Work/HPE/HCAS/hcas_java/find-dev/src/main/resources/hca_config/docview_admissions_linkContent_Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<docview xmlns="http://www.autonomy.com/find/docview"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.autonomy.com/find/docview hca_docview.xsd"
    docRoot="DOCUMENT">
    <viewtab name="Encounter Info">
        <field name="ADMISSION/HADM_ID" label="Encounter ID"></field>
        <field name="ADMISSION/PATIENT/ADMISSION_DATE" label="Admission Date"></field>
        <field name="ADMISSION/PATIENT/DISCHARGE_DATE" label="Discharge Date"></field>
        <field name="ADMISSION/PATIENT/ADMISSION_DATE_YRMON" label="Admission YearMonth"></field>
        <field name="ADMISSION/PATIENT/ADMISSION_DATE_MON_GRP" label="Admission Month"></field>
        <field name="ADMISSION/PATIENT/ADMISSION_DATE_WEEK_GRP" label="Admission Week"></field>
    </viewtab>
    <viewtab name="Patient Info">
        <field name="ADMISSION/PATIENT/SUBJECT_ID" label="Patient ID" contentView="patients" contentQParams="print=fields&amp;printfields=PATIENT/ADMISSION/PATIENT/*" contentTemplate="/WEB-INF/xsl/defaultLinkContent2.xsl"></field>        
    </viewtab>
    
</docview>
