=== Organization-Work/HPE/HCAS/hca_config/table_relations_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
   <schema xmlns="http://www.w3.org/2001/XMLSchema"
  xmlns:vertica="http://www.autonomy.com/vertica/fields"
  targetNamespace="http://www.autonomy.com/vertica/fields"
  elementFormDefault="qualified">


	<complexType name="TableRelationObject">
         <sequence>
				
				<element name="joinNumber" type="int"></element>
				<element name="table" type="string"></element>
				 <element name="refCol" type="string"></element>
				 <element name="joinCol" type="string"></element>
				 <element name="parentTable" type="string"></element>
				 <element name="parentCol" type="string"></element>
				 <element name="extraColumns" type="string"></element>				 
				 <element name="extraParentColumns" type="string"></element>
				 <element name="joinExp" type="string"></element>
				  <element name="whereExp" type="string" minOccurs="0"></element>
		</sequence>
    </complexType>

		 
	<complexType name="TableRelationList">
         <sequence>
				 <element name="view" type="string"></element>				 
				 <element name="relation" type="vertica:TableRelationObject" minOccurs="0" maxOccurs="unbounded"/>               
		</sequence>
    </complexType>
		 
	<element name="TableRelations">
        <complexType>
            <sequence>
                <element name="tableRelationList" type="vertica:TableRelationList" minOccurs="1" maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element> 
	
   </schema>

=== Organization-Work/HPE/HCAS/hca_config/table_relations.xml
<?xml version="1.0" encoding="UTF-8"?>
<TableRelations xmlns="http://www.autonomy.com/vertica/fields"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.autonomy.com/vertica/fields table_relations_1.xsd">
	<tableRelationList>
		<view>inpatient</view>	
		<relation>
			<joinNumber>2</joinNumber>
			<table>d_meditems</table>
			<refCol>itemid</refCol>
			<joinCol>itemid</joinCol>
			<parentTable>medevents_new</parentTable>
			<parentCol>itemid</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>3</joinNumber>
			<table>medevents_new</table>
			<refCol>subject_id</refCol>
			<joinCol>subject_id</joinCol>
			<parentTable>admissions_new_temp</parentTable>
			<parentCol>subject_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>4</joinNumber>
			<table>poe_order_new_temp</table>
			<refCol>hadm_id</refCol>
			<joinCol>hadm_id</joinCol>
			<parentTable>admissions_new_temp</parentTable>
			<parentCol>hadm_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>5</joinNumber>
			<table>poe_med</table>
			<refCol>poe_id</refCol>
			<joinCol>poe_id</joinCol>
			<parentTable>poe_order_new_temp</parentTable>
			<parentCol>poe_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>7</joinNumber>
			<table>d_caregivers</table>
			<refCol>cgid</refCol>
			<joinCol>cgid</joinCol>
			<parentTable>noteevents_new</parentTable>
			<parentCol>cgid</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>8</joinNumber>
			<table>d_careunits</table>
			<refCol>cuid</refCol>
			<joinCol>cuid</joinCol>
			<parentTable>noteevents_new</parentTable>
			<parentCol>cuid</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>9</joinNumber>
			<table>noteevents_new</table>
			<refCol>icustay_id</refCol>
			<joinCol>hadm_id</joinCol>
			<parentTable>admissions_new_temp</parentTable>
			<parentCol>hadm_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp>noteevents_new.cuid = 1</joinExp>
		</relation>
		<relation>
			<joinNumber>10</joinNumber>
			<table>d_labitems</table>
			<refCol>itemid</refCol>
			<joinCol>itemid</joinCol>
			<parentTable>labevents_new</parentTable>
			<parentCol>itemid</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>11</joinNumber>
			<table>labevents_new</table>
			<refCol>hadm_id</refCol>
			<joinCol>hadm_id</joinCol>
			<parentTable>admissions_new_temp</parentTable>
			<parentCol>hadm_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>		
		<relation>
			<joinNumber>12</joinNumber>
			<table>icd9</table>
			<refCol>hadm_id</refCol>
			<joinCol>hadm_id</joinCol>
			<parentTable>admissions_new_temp</parentTable>
			<parentCol>hadm_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>13</joinNumber>
			<table>d_codeditems</table>
			<refCol>itemid</refCol>
			<joinCol>itemid</joinCol>
			<parentTable>drgevents</parentTable>
			<parentCol>itemid</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>15</joinNumber>
			<table>age</table>
			<refCol>hadm_id</refCol>
			<joinCol>hadm_id</joinCol>
			<parentTable>admissions_new_temp</parentTable>
			<parentCol>hadm_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>16</joinNumber>
			<table>drgevents</table>
			<refCol>hadm_id</refCol>
			<joinCol>hadm_id</joinCol>
			<parentTable>admissions_new_temp</parentTable>
			<parentCol>hadm_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>18</joinNumber>
			<table>sex</table>
			<refCol>subject_id</refCol>
			<joinCol>subject_id</joinCol>
			<parentTable>admissions_new_temp</parentTable>
			<parentCol>subject_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>21</joinNumber>
			<table>demographic_detail</table>
			<refCol>hadm_id</refCol>
			<joinCol>hadm_id</joinCol>
			<parentTable>admissions_new_temp</parentTable>
			<parentCol>hadm_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>24</joinNumber>
			<table>d_patients_new</table>
			<refCol>subject_id</refCol>
			<joinCol>subject_id</joinCol>
			<parentTable>admissions_new_temp</parentTable>
			<parentCol>subject_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>27</joinNumber>
			<table>expire</table>
			<refCol>subject_id</refCol>
			<joinCol>hadm_id</joinCol>
			<parentTable>admissions_new_temp</parentTable>
			<parentCol>subject_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>30</joinNumber>
			<table>sex</table>
			<refCol>subject_id</refCol>
			<joinCol>subject_id</joinCol>
			<parentTable>admissions_new_temp</parentTable>
			<parentCol>subject_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>33</joinNumber>
			<table>inpatient_tags</table>
			<refCol>tagid</refCol>
			<joinCol>ref</joinCol>
			<parentTable>admissions_new_temp</parentTable>
			<parentCol>hadm_id</parentCol>
			<extraColumns>ctype</extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>36</joinNumber>
			<table>icustay_detail_new</table>
			<refCol>hadm_id</refCol>
			<joinCol>hadm_id</joinCol>
			<parentTable>admissions_new_temp</parentTable>
			<parentCol>hadm_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>50</joinNumber>
			<table>admissions_new_temp</table>
			<refCol>hadm_id</refCol>
			<joinCol>hadm_id</joinCol>
			<parentTable>admissions_new_temp</parentTable>
			<parentCol></parentCol>
			<extraColumns>subject_id</extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>		
	</tableRelationList>
	<tableRelationList>
		<view>patients</view>	
		<relation>
			<joinNumber>2</joinNumber>
			<table>d_meditems</table>
			<refCol>itemid</refCol>
			<joinCol>itemid</joinCol>
			<parentTable>medevents_new</parentTable>
			<parentCol>itemid</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>3</joinNumber>
			<table>medevents_new</table>
			<refCol>subject_id</refCol>
			<joinCol>subject_id</joinCol>
			<parentTable>patient_master</parentTable>
			<parentCol>subject_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>4</joinNumber>
			<table>poe_order_new_temp</table>
			<refCol>subject_id</refCol>
			<joinCol>subject_id</joinCol>
			<parentTable>patient_master</parentTable>
			<parentCol>subject_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>5</joinNumber>
			<table>poe_med</table>
			<refCol>poe_id</refCol>
			<joinCol>poe_id</joinCol>
			<parentTable>poe_order_new_temp</parentTable>
			<parentCol>poe_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>7</joinNumber>
			<table>d_caregivers</table>
			<refCol>cgid</refCol>
			<joinCol>cgid</joinCol>
			<parentTable>noteevents_new</parentTable>
			<parentCol>cgid</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>8</joinNumber>
			<table>d_careunits</table>
			<refCol>cuid</refCol>
			<joinCol>cuid</joinCol>
			<parentTable>noteevents_new</parentTable>
			<parentCol>cuid</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>9</joinNumber>
			<table>noteevents_new</table>
			<refCol>icustay_id</refCol>
			<joinCol>subject_id</joinCol>
			<parentTable>patient_master</parentTable>
			<parentCol>subject_id</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp>noteevents_new.cuid = 1</joinExp>
		</relation>
		<relation>
			<joinNumber>10</joinNumber>
			<table>d_labitems</table>
			<refCol>itemid</refCol>
			<joinCol>itemid</joinCol>
			<parentTable>labevents_new</parentTable>
			<parentCol>itemid</parentCol>
			<extraColumns></extraColumns>
			<extraParentColumns></extraParentColumns>
			<joinExp></joinExp>
		</relation>
		<relation>
			<joinNumber>11</joinNumber>
